# Generated by Django 5.0.3 on 2024-03-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'смена', 'verbose_name_plural': 'смены'},
        ),
    ]
