# Generated by Django 5.0.3 on 2024-03-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='services',
            field=models.IntegerField(default=0, verbose_name='Дополнительные услуги'),
        ),
    ]
