# Generated by Django 5.0.3 on 2024-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
