# Generated by Django 5.0.3 on 2024-04-07 13:19

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shift_rate',
            field=models.IntegerField(validators=[projects.validators.RateValidator.validate_rate], verbose_name='Стоимость смены'),
        ),
    ]
