# Generated by Django 5.0.3 on 2024-03-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало смены')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец смены')),
                ('shift_cost', models.IntegerField(verbose_name='цена за смену')),
                ('overwork_hours', models.PositiveSmallIntegerField(default=0, verbose_name='часы переработки')),
                ('overwork_cost', models.PositiveIntegerField(default=0, verbose_name='сумма переработок')),
                ('non_sleep_hours', models.PositiveSmallIntegerField(default=0, verbose_name='часы недосыпа')),
                ('non_sleep_cost', models.PositiveIntegerField(default=0, verbose_name='сумма недосыпов')),
                ('current_lunch', models.PositiveIntegerField(default=0, verbose_name='текущий обед')),
                ('late_lunch', models.PositiveIntegerField(default=0, verbose_name='поздний обед')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='итого')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='смены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.telegramuser')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
