# Generated by Django 5.0.3 on 2024-03-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id'], 'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.AddField(
            model_name='report',
            name='is_current_lunch',
            field=models.BooleanField(default=False, verbose_name='текущий обед'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_late_lunch',
            field=models.BooleanField(default=False, verbose_name='поздний обед'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='проект'),
        ),
    ]
