# Generated by Django 5.0.3 on 2024-03-19 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало смены'),
        ),
    ]
