# Generated by Django 5.0.3 on 2024-03-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_report_is_current_lunch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='non_sleep_cost',
            new_name='non_sleep_rate',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='overwork_cost',
            new_name='overwork_rate',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='shift_cost',
            new_name='shift_rate',
        ),
    ]
