name: kinosmena workflow

on:
  push:
    branches: [develop]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Repo
        uses:  actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kinosmena_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # Выполняет pull образа с DockerHub <имя-пользователя>/<имя-репозитория>
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/kinosmena_backend 
            # остановка всех контейнеров
            # sudo docker stop $(sudo docker ps -a -q)
            # Остановка контейнера kinosmena_container
            sudo docker stop kinosmena_container
            sudo docker run --rm -d -p 6080:6080 --name kinosmena_container ${{ secrets.DOCKER_USERNAME }}/kinosmena_backend
